completed basic info page but button still needs to be done
UT-Application-Development-Association/ADA-Website pull request #15
Opened 2020-11-09 08:15 UTC by chouche9

2020-11-12 03:56 UTC, Falanke21 requested changes

2020-11-12 03:56 UTC, Falanke21 commented on src/assets/img/triangle-left.svg
> +<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg class="icon" width="200px" height="200.00px" viewBox="0 0 1
Is this file and triangle-right.svg used anywhere in this commit? If no, these .svg files should not be included in this commit.

2020-11-12 03:56 UTC, Falanke21 commented on src/pages/Main.js
> +import { Button } from "react-bootstrap";
Same with this, it is declared but never used.

2020-11-12 03:56 UTC, Falanke21 commented on src/styles/main_page/_Main.scss
> +    align-items: center;
Why making this a flex? I don't get why you are changing this arrow button 😂

2020-11-12 03:56 UTC, Falanke21 commented on src/styles/main_page/_Common.scss
> +.my-button {
Same with this. If this code doesn't do anything, we don't need it in the commit

2020-11-12 03:56 UTC, Falanke21 commented on src/styles/main_page/_Common.scss
> +.right {
Same with this.

2020-11-12 03:58 UTC, Falanke21 commented
Besides the code style, the layout looks very pretty to me. 👍

2020-11-14 03:29 UTC, Falanke21 commented
👮‍♂️💪👍

2021-01-18 01:51 UTC, rainyuxuan reviewed
I changed some code structure in the files, please continue working on Frank's review.

2021-01-19 05:26 UTC, rainyuxuan commented
The problem I made during the last meeting was caused by the unwatched sass. It is now solved and I removed the css and css.map files. 😅

2021-01-28 02:29 UTC, rainyuxuan approved these changes
All solved

2021-02-01 00:48 UTC, Falanke21 approved these changes
I will merge this, but the mobile-adaption still needs to be done

2021-02-01 00:49 UTC, merged