Yupeng timeline feature
UT-Application-Development-Association/ADA-Website pull request #21
Opened 2020-12-06 22:02 UTC by fmt47

This is the timeline with 6 events demo. The timeline now has features below;
- event name
- event picture
- scroll horizontally
- picture hover effect

TODO:
- function to add an event to the timeline, input would be (event name, link, picture)
- add two buttons (left, right) for the mouse users to control the timeline

2020-12-06 23:28 UTC, rainyuxuan requested changes
Good job 👍

2020-12-06 23:28 UTC, rainyuxuan commented on src/styles/main_page/_Common.scss
> +    }
If not necessary, try not to change Common.scss. This might break other people's style.

2020-12-06 23:29 UTC, rainyuxuan commented
Equal vertical padding might look better.

![image](https://user-images.githubusercontent.com/42298884/101296344-e3e44a00-37f0-11eb-959e-f0d27e57766c.png)

2020-12-12 00:48 UTC, Falanke21 reviewed
Nice work!

2020-12-12 00:48 UTC, Falanke21 commented on src/components/main_page/Timeline.js
> +            <div className="heading-container container" style={{overflow:"hidden", height:"500px"}}>
For consistency, I suggest moving all style related CSS inside scss files.

2020-12-12 00:48 UTC, Falanke21 commented on src/pages/Main.js
> +          <Timeline text="TIMELINE"/>
I think we have a Header component already? Is the text prop necessary?

2021-01-20 01:32 UTC, rainyuxuan requested changes
Nice work! 👍👍👍

2021-01-20 01:32 UTC, rainyuxuan commented on src/components/main_page/Timeline.js
> +                <div className="heading-line white"></div>
You can use the Heading.js component.

2021-01-20 01:32 UTC, rainyuxuan commented on src/components/main_page/Timeline.js
> +                    </div>
You can create TimelineEvent component to simplify this part.

2021-01-20 01:32 UTC, rainyuxuan commented on src/pages/Main.js
> +        </div>
You don't need the `div` outside the `Timeline`.

2021-01-20 01:32 UTC, rainyuxuan commented on src/styles/Style.scss
> +@import "main_page/Timeline"
Move this line to line 6 can be better and more organized.

2021-01-20 01:32 UTC, rainyuxuan commented on src/styles/main_page/_Timeline.scss
> +
Maybe you want to put these into an outer container so that it does not cause conflicts.

2021-01-20 01:32 UTC, rainyuxuan commented on src/styles/main_page/_Timeline.scss
> +    position: absolute;
Is there any other way that can avoid using `absolute`?

2021-01-20 01:32 UTC, rainyuxuan commented on src/components/main_page/Timeline.js
> +                        <div className="event-picture"></div>
Pictures were uploaded into Google drive. Try to add some into your code, see if they work well.

2021-05-01 01:23 UTC, rainyuxuan approved these changes

2021-05-01 02:54 UTC, merged